let display = document.getElementById("input"); // Access the input Element...
let buttons = document.querySelectorAll('.btn-1'); // Access the Buttons...
let mymusic = new Audio('music.wav'); // Add Music

let buttonsArray = Array.from(buttons); // Convert into Array...
let string = ""; // Assume a Empty String...

buttonsArray.forEach((button)=>{        // Use for each for accessing each button...
    button.addEventListener('click',(e)=>{  // Add event listner on each button clicked...

        mymusic.play();

        if(e.target.innerHTML == 'DE') {    // if user clicked on DE delete one previous number...
            string = string.substring(0,string.length-1)
            display.value = string;
        }
        else if(e.target.innerHTML == 'AC'){    // if user clicked on AC clear the Screen...
                string = "";
                display.value = string
        }
        else if(e.target.innerHTML == '='){ // if user clicked on = evaluate the numbers...
            string =eval(string);
            display.value = string
    }
        else {                              // if user clicked on Any of the number display it on the screen...
            string += e.target.innerHTML;
            display.value = string;
        }
        
    });
});